### PR TITLE
Port iwasm to SGX to enable a restricted version of interpreter run in SGX

### PR DESCRIPTION
**Pull request by wenyongh**

### CODE REVIEW

**Comment by cmickeyb** [comment]
merging this (passes all my tests). however, putting an sgx specific file into the libc runtime directory seems inconsistent with putting all platform specific code into one of the product directories. i'll let you figure out the clean way to make it work. just happy to have something i can use!!!!

**Comment by wenyongh** [comment]
OK, it is a temporary method to enable the code. I am confused why you add macros OPS_INPUT_OUTPUT and OPS_UNSAFE_BUFFERS in file libc_wrappe.c, the memory buffer allocated in this file is also inside Enclave, it is allocated from the wasm app heap, which is inside Enclave. So the buffer should be safe.
I suggest to use the normal version of libc_wrapper.c, modify several places of printf to bh_printf, and comment  the code using stdout/stdin/stderr, and have a try.

**Comment by cmickeyb** [comment]
OPS_INPUT_OUTPUT is necessary because you cannot link the library in an sgx
application since most of the IO operations are unsupported (there is no
stdout or stderr).

OPS_UNSAFE_BUFFERS (which we can change the name) is necessary because we
cannot pass a security review for our code so long as it include the str*
functions which do not handle bounds checks. the wrappers you have around
them are not sufficient to make those routines safe enough for our
reviewers. if we could replace those functions with bounded versions like
strcpy_s and strncpy_s. I have not looked at the memory management
functions in WAMR, but if you have the size of the allocated object then it
could be passed into those functions explicitly to make them bounds safe.

**Comment by wenyongh** [comment]
For the printf like wrapper functions, including printf/sprintf/snprintf/puts/putchar, they actually don't use stdout/stderr, they call printf function. So could you remove OPS_INPUT_OUTPUT for them, and just modify calling printf to calling bh_printf?

The stdout and stderr are only used in function wasm_native_global_lookup(), you can add macro to comment them.

It is really difficult to check the string length for str* functions, if we check their characters one by one,  the performance will be not so good. So if you want, you can add a macro to comment them.

Actually you didn't modify the implementation of these functions, so I suggest to use the same libc_wrapper.c file, and:
(1) modify printf to bh_printf
(2) add macro for some places, using #ifndef but not #ifdef, so by default the code is enabled. If you want to disable them, just add_definitions(macro) in your CMakeLists.txt.

What's your opinion?

**Pull request merged**
